### PR TITLE
Reorganize and add app info

### PR DESCRIPTION
**Pull request by klmhsb42**
This is how I would organize and add app info. #412 What do you think? From where does it get `<%= info.app.description %>` I would like to add content.

### CODE REVIEW

**Comment by cyberb** [comment]
app info actually comes from snap syncloud store info:
https://github.com/syncloud/snapd/blob/release-2.43/store/syncloud.go#L101

which comes from here:
https://github.com/syncloud/release/blob/master/index-v2

Probably description does not work right now.

**Comment by cyberb** [comment]
Do you have a screenshot for this change?
Actually if your the build locally you will get all the screenshots in artifact sir.

**Comment by klmhsb42** [comment]
screenshot
screenshot2

**Comment by klmhsb42** [comment]
> Probably description does not work right now.

Yes

> app info actually comes from snap syncloud store info:
> https://github.com/syncloud/snapd/blob/release-2.43/store/syncloud.go#L101

Probably because "description" is missing here.

**Comment by klmhsb42** [comment]
I would put all description and detail information in an own popup as details might be confusing for non-technicals and if the upgrade button appears, everybody still knows what to do. I would also add more details like licence, channel, etc. (Some information you have already in _syncloud.go_ file.)

**Comment by klmhsb42** [comment]
(It would be nice to have later a second button, which is a star, which would also open an own popup window, in which you can rate/comment the app.)

**Comment by cyberb** [comment]
Should we close this pull request as it is not ready?

**Comment by klmhsb42** [comment]
Yes

**Pull request closed without merging**
